### ISSUE TITLE
Display search result score during user testing

### ISSUE THREAD

**Issue by Bisaloo** [epiverse-connect/epiverse-search-frontend#1]
If we go with option 2 in https://github.com/epiverse-connect/epiverse-search/issues/17 (which seemed to be the WHO preference), we will need to figure out the value of this threshold through user testing.

For this, we would need to have the score value (as defined in https://github.com/epiverse-connect/epiverse-search/blob/a442a326cf9a8772cc9255e0852c12b8a5a6bfec/design/api-design.md?plain=1#L31) displayed next to the search result during user testing.

**Comment by chartgerink** [comment]
I can add this to the front-end easily, and will try something out to get us started.

**Comment by chartgerink** [comment]
Added in fa6c696f13ed2483dce0453526e822c7475d5ee2
